"""
FUJIN-P Configuration Template

このファイルをコピーして config.py に名前を変え、
各プレースホルダー <YOUR_...> を実際の値に書き換えてください。

Generated by migrate_fujinp_scions (さいまる): 2026-09-07 00:39 JST
"""

# !! このファイルは config.py から自動生成されたテンプレートです !!
# !! <YOUR_...> を実際の値に置き換えて config.py として保存 !!

# ---------------------------------------------------------
# ⚠ 自動匿名化できなかった／機械的に処理した箇所があります。
#   下記を必ず目視で確認してください。
# ---------------------------------------------------------
#   - SECRET_KEY: 単純な代入ではないため機械的に伏せ字化しました。構文が壊れていないか確認してください
#   - SESSION_COOKIE_SAMESITE の値を伏せ字化しました
#   - GOOGLE_CLIENT_ID の値を伏せ字化しました
#   - GOOGLE_CLIENT_SECRET の値を伏せ字化しました
#   - SLACK_USER_TOKEN の値を伏せ字化しました
#   - DRIVE_CLIENT_ID の値を伏せ字化しました
#   - DRIVE_CLIENT_SECRET の値を伏せ字化しました
#   - DRIVE_REDIRECT_URI の値を伏せ字化しました
#   - DRIVE_REFRESH_TOKEN の値を伏せ字化しました
#   - MAIL_SERVER の値を伏せ字化しました
#   - MAIL_USERNAME の値を伏せ字化しました
#   - MAIL_PASSWORD の値を伏せ字化しました
#   - MAIL_DEFAULT_SENDER の値を伏せ字化しました
#   - DB_ACCOUNT の値を伏せ字化しました
#   - BASE_URL の値を伏せ字化しました
#   - DB_HOST の値を伏せ字化しました
#   - DB_USER の値を伏せ字化しました
#   - DB_PASSWORD の値を伏せ字化しました
#   - DB_DEFAULT: 単純な代入ではないため機械的に伏せ字化しました。構文が壊れていないか確認してください
#   - DB_FUJINP: 単純な代入ではないため機械的に伏せ字化しました。構文が壊れていないか確認してください
#   - DB_PUBLIC: 単純な代入ではないため機械的に伏せ字化しました。構文が壊れていないか確認してください
#   - ALLOWED_EXTENSIONS: 単純な代入ではないため機械的に伏せ字化しました。構文が壊れていないか確認してください
#   - COLREP_ADMIN_CATEGORY の値を伏せ字化しました
#   - SLACK_BOT_TOKEN の値を伏せ字化しました
#   - ANTHROPIC_API_KEY の値を伏せ字化しました
#   - FUJINP_REPO_DIR の値を伏せ字化しました
#   - GITHUB_TOKEN の値を伏せ字化しました

"""
FUJIN-P Configuration Template

このファイルをコピーして config.py に名前を変え、
各プレースホルダー <YOUR_...> を実際の値に書き換えてください。

Generated by migrate_fujinp_scions (さいまる): 2026-07-21 22:26 JST
"""

# !! このファイルは config.py から自動生成されたテンプレートです !!
# !! <YOUR_...> を実際の値に置き換えて config.py として保存 !!

import os
from datetime import timezone, timedelta

class Config:

    # ===== 基本設定 =====
    # ⚠ 要確認: 自動匿名化できません。値を目視で確認してください (SECRET_KEY)
    SECRET_KEY = os.environ.get('<YOUR_SECRET_KEY>') or '<YOUR_SECRET_KEY>'
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = '<YOUR_SESSION_COOKIE_SAMESITE>'
    PERMANENT_SESSION_LIFETIME = 86400  # 24時間

    # ===== Google OAuth（環境変数優先） =====
    GOOGLE_CLIENT_ID = '<YOUR_GOOGLE_CLIENT_ID>'
    GOOGLE_CLIENT_SECRET = '<YOUR_GOOGLE_CLIENT_SECRET>'

    # ===== Slack設定 =====
    SLACK_USER_TOKEN = '<YOUR_SLACK_USER_TOKEN>'
    SLACK_TEAM_ID = '<YOUR_SLACK_TEAM_ID>'

    # ===== Google Drive（大学アカウント・ウラルス用） =====
    DRIVE_CLIENT_ID = '<YOUR_DRIVE_CLIENT_ID>'
    DRIVE_CLIENT_SECRET = '<YOUR_DRIVE_CLIENT_SECRET>'
    DRIVE_REDIRECT_URI = '<YOUR_DRIVE_REDIRECT_URI>'
    DRIVE_REFRESH_TOKEN = '<YOUR_DRIVE_REFRESH_TOKEN>'



    # タイムゾーン
    JST = timezone(timedelta(hours=9))

    # ===== メール設定（環境変数優先） =====
    MAIL_SERVER = '<YOUR_MAIL_SERVER>'
    MAIL_PORT = 587
    MAIL_USE_TLS = True
    MAIL_USERNAME='<YOUR_MAIL_USERNAME>'
    MAIL_PASSWORD='<YOUR_MAIL_PASSWORD>'
    MAIL_DEFAULT_SENDER = '<YOUR_MAIL_DEFAULT_SENDER>'

    # ===== プラットフォーム設定 =====
    DB_ACCOUNT = '<YOUR_DB_ACCOUNT>'
    UPLOAD_BASE_DIR = '<YOUR_UPLOAD_BASE_DIR>'
    BASE_URL = '<YOUR_BASE_URL>'

    # ===== データベース接続情報 =====
    DB_HOST = '<YOUR_DB_HOST>'
    DB_USER = '<YOUR_DB_USER>'
    DB_PASSWORD = '<YOUR_DB_PASSWORD>'  # 本番環境では環境変数推奨

    # ===== データベース名（自動生成） =====
    # ⚠ 要確認: 自動匿名化できません。値を目視で確認してください (DB_DEFAULT)
    DB_DEFAULT = f'<YOUR_DB_DEFAULT>'
    # ⚠ 要確認: 自動匿名化できません。値を目視で確認してください (DB_FUJINP)
    DB_FUJINP = f'<YOUR_DB_FUJINP>'
    # ⚠ 要確認: 自動匿名化できません。値を目視で確認してください (DB_PUBLIC)
    DB_PUBLIC = f'<YOUR_DB_PUBLIC>'


    # CoRePo設定
    COLREP_PROJECTS_TABLE = '<YOUR_COLREP_PROJECTS_TABLE>'
    UPLOAD_FOLDER = '<YOUR_UPLOAD_FOLDER>'
    # ⚠ 要確認: 自動匿名化できません。値を目視で確認してください (ALLOWED_EXTENSIONS)
    ALLOWED_EXTENSIONS = {'<YOUR_ALLOWED_EXTENSIONS>', '<YOUR_ALLOWED_EXTENSIONS>', '<YOUR_ALLOWED_EXTENSIONS>', '<YOUR_ALLOWED_EXTENSIONS>', '<YOUR_ALLOWED_EXTENSIONS>'}
    COLREP_ADMIN_CATEGORY = "<YOUR_COLREP_ADMIN_CATEGORY>"
    COLREP_MANAGER_FEATURE = "<YOUR_COLREP_MANAGER_FEATURE>"

    # テーシャ用設定
    TABLE_SHARE_SECRET = '<YOUR_TABLE_SHARE_SECRET>'  # 暗号化用シークレット
    TABLE_SHARE_API_KEY = '<YOUR_TABLE_SHARE_API_KEY>'    # 他サイトに提供するAPIキー

    # ゆーまい関係
    SITE_URL = "<YOUR_SITE_URL>"  # 自サイトのURL
    SITE_DISPLAY_NAME = "<YOUR_SITE_DISPLAY_NAME>"

    # 倫理審査用
    SLACK_BOT_TOKEN              = '<YOUR_SLACK_BOT_TOKEN>'
    ETHICS_SLACK_CHANNEL_ID      = '<YOUR_ETHICS_SLACK_CHANNEL_ID>'

    # ===== キターレ連携申請審査用 =====
    EXT_ENGAGEMENT_SLACK_CHANNEL_ID = '<YOUR_EXT_ENGAGEMENT_SLACK_CHANNEL_ID>'

    # ===== キターレオンライン審議用 =====
    KITARE_SLACK_CHANNEL_ID     = '<YOUR_KITARE_SLACK_CHANNEL_ID>'
    KITARE_DEADLINE_BATCH_TOKEN = '<YOUR_KITARE_DEADLINE_BATCH_TOKEN>'  # 締切バッチURL保護用

    # ===== ふっこ（Claude APIデモ）用 =====
    ANTHROPIC_API_KEY = '<YOUR_ANTHROPIC_API_KEY>'  # Anthropic ConsoleのAPIキー（秘匿情報）
    FUKKO_MODEL       = '<YOUR_FUKKO_MODEL>'          # 使用モデル
    FUKKO_MAX_TOKENS  = 1024                        # レスポンス最大トークン数

    # ===== 通知サブシステム用 =====
    TABLE_POST_SLACK_CHANNEL = '<YOUR_TABLE_POST_SLACK_CHANNEL>'

    # ===== アプシャ GitHub 連携 =====
    FUJINP_REPO_DIR = '<YOUR_FUJINP_REPO_DIR>'
    GITHUB_TOKEN = '<YOUR_GITHUB_TOKEN>'   # fine-grained PAT（fujin-p 限定・Contents: Read and write）

##### Classの定義ここまで


class DevelopmentConfig(Config):
    DEBUG = True

class ProductionConfig(Config):
    DEBUG = False
    SESSION_COOKIE_SECURE = True

config = {
    'development': DevelopmentConfig,
    'production': ProductionConfig,
    'default': DevelopmentConfig
}
