-- 事業全貌（mid_term_progress）の中核となる常設4表（fujinp の DB に作る）
-- nishida$fujinp の実物（SHOW CREATE TABLE，2026-09-29）と同じ定義．事業全貌が単独で動くのに必要な表
-- editor_memo・owner_memo・response_to_committee など，事業全貌がまだ使わない列も実物どおりに含める
CREATE TABLE IF NOT EXISTS `T_mid_plan_details` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `term` int NOT NULL,
  `sub_term` int NOT NULL,
  `valid_from` int DEFAULT NULL COMMENT '有効開始年度',
  `valid_to` int DEFAULT NULL COMMENT '有効終了年度',
  `mid_goal_no` int NOT NULL,
  `goal_chapter` varchar(10) DEFAULT NULL COMMENT '章（例 4-1, 5）',
  `goal_chapter_title` varchar(255) DEFAULT NULL COMMENT '章の標題（例 教育に関する目標）',
  `goal_section` int DEFAULT NULL COMMENT '節（（１）→1）',
  `goal_section_title` varchar(255) DEFAULT NULL COMMENT '節の標題（例 教育の成果）',
  `goal_item` int DEFAULT NULL COMMENT '目標の丸数字（①→1）',
  `goal_item_title` varchar(255) DEFAULT NULL COMMENT '目標の丸数字の標題',
  `mid_goal_text` text,
  `mid_plan_no` int NOT NULL,
  `measure_no` int DEFAULT NULL COMMENT '措置の番号（①→1．番号なしはNULL）',
  `measure_title` varchar(255) DEFAULT NULL COMMENT '措置の標題（例 教育課程の編成）',
  `measure_sub` varchar(20) DEFAULT NULL COMMENT '措置の下の段（ア，イ(ア) など）',
  `measure_sub_title` varchar(255) DEFAULT NULL COMMENT '措置の下の段の標題',
  `mid_plan_text` text,
  `detail_no` int NOT NULL,
  `owner_group` varchar(100) DEFAULT NULL,
  `progress_text` text,
  `result_text` text,
  `self_eval` tinyint DEFAULT NULL,
  `self_eval_reason` text,
  `editor_memo` text,
  `owner_memo` text,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `updated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_mid_plan_detail` (`term`,`sub_term`,`mid_plan_no`,`detail_no`),
  KEY `ix_mid_plan_sub_term` (`sub_term`),
  KEY `ix_mid_plan_owner` (`owner_group`),
  CONSTRAINT `ck_mid_detail_no` CHECK ((`detail_no` >= 1)),
  CONSTRAINT `ck_mid_detail_self_eval` CHECK (((`self_eval` is null) or (`self_eval` between 1 and 4)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `T_mid_plan_evaluations` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `term` int NOT NULL,
  `sub_term` int NOT NULL,
  `mid_plan_no` int NOT NULL,
  `phase` varchar(10) NOT NULL,
  `self_eval` tinyint DEFAULT NULL,
  `self_eval_reason` text,
  `committee_eval` tinyint DEFAULT NULL,
  `committee_comment` text,
  `response_to_committee` text,
  `editor_memo` text,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `updated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_mid_plan_eval` (`term`,`sub_term`,`mid_plan_no`,`phase`),
  KEY `ix_mid_eval_sub_term` (`sub_term`),
  CONSTRAINT `ck_mid_eval_committee_eval` CHECK (((`committee_eval` is null) or (`committee_eval` between 1 and 4))),
  CONSTRAINT `ck_mid_eval_phase` CHECK ((`phase` in (_utf8mb4'progress',_utf8mb4'result'))),
  CONSTRAINT `ck_mid_eval_self_eval` CHECK (((`self_eval` is null) or (`self_eval` between 1 and 4)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `T_ann_plan_details` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `fiscal_year` int NOT NULL,
  `mid_plan_no` int NOT NULL,
  `annual_plan_no` int NOT NULL,
  `detail_no` int NOT NULL,
  `owner_group` varchar(100) DEFAULT NULL,
  `plan_text` text,
  `progress_text` text,
  `result_text` text,
  `self_eval` tinyint DEFAULT NULL,
  `self_eval_reason` text,
  `editor_memo` text,
  `owner_memo` text,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `updated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ann_plan_detail` (`fiscal_year`,`mid_plan_no`,`annual_plan_no`,`detail_no`),
  KEY `ix_ann_plan_owner` (`owner_group`),
  CONSTRAINT `ck_ann_detail_no` CHECK ((`detail_no` >= 1)),
  CONSTRAINT `ck_ann_detail_self_eval` CHECK (((`self_eval` is null) or (`self_eval` between 1 and 4)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `T_ann_plan_evaluations` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `fiscal_year` int NOT NULL,
  `mid_plan_no` int NOT NULL,
  `annual_plan_no` int NOT NULL,
  `self_eval` tinyint DEFAULT NULL,
  `self_eval_reason` text,
  `self_eval_status` enum('drafting','approved') DEFAULT 'drafting' COMMENT '自己評価のとりまとめ：とりまとめ中／承認済み',
  `committee_eval` tinyint DEFAULT NULL,
  `committee_comment` text,
  `response_to_committee` text,
  `editor_memo` text,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `updated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ann_plan_eval` (`fiscal_year`,`mid_plan_no`,`annual_plan_no`),
  CONSTRAINT `ck_ann_plan_committee_eval` CHECK (((`committee_eval` is null) or (`committee_eval` between 1 and 4))),
  CONSTRAINT `ck_ann_plan_self_eval` CHECK (((`self_eval` is null) or (`self_eval` between 1 and 4)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
